"""Regenerate the downloadable CSV copies under docs/_static/data/.

The docs offer a few reference tables as downloads. Those copies used to be
made by hand, with no recorded relationship to the data they came from, so they
could drift silently. This regenerates them from src/data/ and writes a
MANIFEST.txt recording each source path and its hash;
tests/test_docs_data.py fails when the two disagree.

    python docs/make_static_data.py

Not packaged, and not run at build time -- run it when the source data changes
and commit the result.
"""

import datetime
import hashlib
import os
import shutil
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "src"))

from ncaa_bbStats._paths import data_path  # noqa: E402

STATIC = os.path.join(HERE, "_static", "data")

# Files copied verbatim: (source under src/data, destination under _static/data).
VERBATIM = [
    (("team_names_stats", "all_div_teams.csv"), ("team_names_stats", "all_div_teams.csv")),
    (("team_names_stats", "all_div_teams_standardized.csv"),
     ("team_names_stats", "all_div_teams_standardized.csv")),
    (("team_names_stats", "team_name_mapping.csv"),
     ("team_names_stats", "team_name_mapping.csv")),
    (("mlb_team_names", "drafted_by_teams.csv"), ("mlb_team_names", "drafted_by_teams.csv")),
    (("mlb_team_names", "drafted_from_schools.csv"),
     ("mlb_team_names", "drafted_from_schools.csv")),
    (("league_constants", "batting_weights.csv"),
     ("league_constants", "batting_weights.csv")),
    (("league_constants", "pitching_constants.csv"),
     ("league_constants", "pitching_constants.csv")),
]

# Player rosters, published as a name index rather than a full stat dump.
ROSTER_COLUMNS = ["name", "team", "team name", "division", "year", "qualified"]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    entries = []

    for source_parts, dest_parts in VERBATIM:
        source = data_path(*source_parts)
        if not os.path.isfile(source):
            print(f"skip (absent): {os.path.join(*source_parts)}")
            continue
        dest = os.path.join(STATIC, *dest_parts)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        shutil.copyfile(source, dest)
        entries.append((os.path.join("src", "data", *source_parts),
                        os.path.join(*dest_parts), sha256(source),
                        sum(1 for _ in open(source, encoding="utf-8")) - 1))
        print(f"copied  {os.path.join(*dest_parts)}")

    for stat_type in ("batting", "pitching"):
        source = data_path("player_stats_cache", stat_type, f"{stat_type}.csv")
        if not os.path.isfile(source):
            print(f"skip (absent): {stat_type}.csv")
            continue
        df = pd.read_csv(source)
        roster = df[[c for c in ROSTER_COLUMNS if c in df.columns]]
        roster = roster.drop_duplicates().sort_values(["year", "team", "name"])

        dest_parts = ("player_stats", f"{stat_type}_players.csv")
        dest = os.path.join(STATIC, *dest_parts)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        roster.to_csv(dest, index=False, lineterminator="\n")
        entries.append((os.path.join("src", "data", "player_stats_cache",
                                     stat_type, f"{stat_type}.csv"),
                        os.path.join(*dest_parts), sha256(source), len(roster)))
        print(f"derived {os.path.join(*dest_parts)}  ({len(roster):,} rows)")

    # The old *DOC.csv snapshots predate the public rewrite and were derived
    # from data this package no longer ships.
    for stale in ("batting_noMinDOC.csv", "batting_qualifiedDOC.csv",
                  "pitching_noMinDOC.csv", "pitching_qualifiedDOC.csv"):
        path = os.path.join(STATIC, "player_stats", stale)
        if os.path.isfile(path):
            os.remove(path)
            print(f"removed {os.path.join('player_stats', stale)}")

    manifest = os.path.join(STATIC, "MANIFEST.txt")
    with open(manifest, "w", encoding="utf-8") as f:
        f.write("# Generated by docs/make_static_data.py -- do not edit.\n")
        f.write(f"# Generated {datetime.date.today().isoformat()}\n")
        f.write("# source\tpublished\tsource_sha256\trows\n")
        for source, dest, digest, rows in sorted(entries):
            f.write(f"{source}\t{dest}\t{digest}\t{rows}\n")
    print(f"\nwrote {os.path.relpath(manifest, HERE)}  ({len(entries)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
